/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 29-mar.-2020 10:22:15 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS banco_calenio CASCADE
;

DROP TABLE IF EXISTS banco_corresponsal CASCADE
;

DROP TABLE IF EXISTS banco_del_beneficiario CASCADE
;

DROP TABLE IF EXISTS beneficiario CASCADE
;

DROP TABLE IF EXISTS Cliente CASCADE
;

DROP TABLE IF EXISTS comision CASCADE
;

DROP TABLE IF EXISTS comisiones_del_giro CASCADE
;

DROP TABLE IF EXISTS comprobante_recibo_giro CASCADE
;

DROP TABLE IF EXISTS cuenta_giros CASCADE
;

DROP TABLE IF EXISTS despachador_giros CASCADE
;

DROP TABLE IF EXISTS detalle_cuenta_de_giros CASCADE
;

DROP TABLE IF EXISTS detalles_actividad_cuenta CASCADE
;

DROP TABLE IF EXISTS fondo CASCADE
;

DROP TABLE IF EXISTS Giro CASCADE
;

DROP TABLE IF EXISTS giro_pagado CASCADE
;

DROP TABLE IF EXISTS historial_estado_de_cuenta CASCADE
;

DROP TABLE IF EXISTS Negociacion CASCADE
;

DROP TABLE IF EXISTS notas_cuenta CASCADE
;

DROP TABLE IF EXISTS oferta_de_prestamo_encontrada CASCADE
;

DROP TABLE IF EXISTS Ordenante CASCADE
;

DROP TABLE IF EXISTS Pais CASCADE
;

DROP TABLE IF EXISTS Producto CASCADE
;

DROP TABLE IF EXISTS productos_en_oferta CASCADE
;

DROP TABLE IF EXISTS tipo_de_producto CASCADE
;

/* Create Tables */

CREATE TABLE banco_calenio
(
	id_banco_calenio bigint NOT NULL,
	nombre_bco varchar(50) NULL,
	direccion_bco varchar(50) NULL,
	tel_bco bigint NULL,
	nit_bco bigint NULL,
	comision_banco_calenio double precision NULL,
	giro_verificar boolean NULL,
	hora_recepcion_giro time without time zone NULL,
	fecha_recepcion_giro date NULL,
	id_despachador_giro bigint NULL
)
;

CREATE TABLE banco_corresponsal
(
	id_banco_corresponsal bigint NOT NULL,
	paga_gastos_ordenante varchar(50) NULL,
	paga_gastos_beneficiario varchar(50) NULL,
	se_comparten_los_gastos varchar(50) NULL,
	id_banco bigint NULL,
	id_despachador_giros bigint NULL,
	id_despachador_giro bigint NULL
)
;

CREATE TABLE banco_del_beneficiario
(
	id_banco_del_beneficiario bigint NOT NULL,
	nombre_del_banco varchar(50) NULL,
	direccion varchar(50) NULL,
	numero_cuenta bigint NULL,
	id_despachador_giros bigint NULL,
	id_despachador_giro bigint NULL
)
;

CREATE TABLE beneficiario
(
	id_beneficiario bigint NOT NULL,
	nombre varchar(50) NULL,
	apellidos varchar(50) NULL,
	razon_social varchar(50) NULL,
	direccion varchar(50) NULL,
	id_despachador_giros bigint NULL,
	id_despachador_giro bigint NULL
)
;

CREATE TABLE Cliente
(
	id_Cliente integer NOT NULL,
	id_Nivel_de_Cliente varchar(50) NULL,
	departamento varchar(50) NULL,
	id_nacionalidad varchar(50) NULL,
	tipo_documento varchar(50) NULL,
	nombres varchar(50) NULL,
	"apellido_materº" varchar(50) NULL,
	razon_Social varchar(50) NULL,
	ciudad varchar(50) NULL,
	estado_civil varchar(50) NULL,
	id_telefono varchar(50) NULL,
	email varchar(50) NULL
)
;

CREATE TABLE comision
(
	id_banco_emisor bigint NULL,
	id_banco_pagador bigint NULL,
	id_banco_calenio bigint NOT NULL,
	id_giro bigint NULL,
	costo_envio double precision NULL,
	id_despachador_giros bigint NULL,
	id_despachador_giro bigint NULL
)
;

CREATE TABLE comisiones_del_giro
(
	id_comisiones_del_giro bigint NOT NULL,
	id_giro varchar(50) NULL,
	id_tarifa varchar(50) NULL,
	frecuencia_de_tarifa varchar(50) NULL,
	estado varchar(50) NULL,
	fecha_inicio date NULL,
	fecha_termino date NULL,
	cantidad_comisiones_por_giro integer NULL,
	cuantia varchar(50) NULL,
	id_pago bigint NULL
)
;

CREATE TABLE comprobante_recibo_giro
(
	id_comprobante_recibo_giro bigint NOT NULL,
	valor_del_giro double precision NULL,
	comision double precision NULL,
	valor_a_pagar double precision NULL,
	fecha_pago date NULL,
	hora time without time zone NULL,
	nombre_de_receptor varchar(50) NULL,
	apellido_m_receptor varchar(50) NULL,
	apellido_p_receptor varchar(50) NULL,
	id_receptor bigint NULL,
	id_girador bigint NULL,
	id_giro bigint NULL,
	id_despachador_giros bigint NULL,
	id_despachador_giro bigint NULL
)
;

CREATE TABLE cuenta_giros
(
	id_cuenta_giros bigint NOT NULL,
	id_persona_recibe bigint NULL,
	id_estado_del_giro bigint NULL,
	id_giro bigint NULL,
	id_notas_cuenta varchar(50) NULL,
	valor_del_giro double precision NULL,
	idUsuario bigint NULL
)
;

CREATE TABLE despachador_giros
(
	id_despachador_giro bigint NOT NULL,
	hora_recepcion_giro time without time zone NULL,
	fecha_recepcion_giro date NULL,
	id_giro bigint NULL,
	comision_giro varchar(50) NULL,
	valor_giro varchar(50) NULL,
	id_su_red bigint NULL,
	id_matrix_giros_servicios bigint NULL,
	id_efectivos_ltda bigint NULL,
	id_servientrega bigint NULL,
	id_efecty bigint NULL,
	id_super_giros bigint NULL,
	id_movil_red bigint NULL,
	id_invercosta bigint NULL,
	id_coopetran bigint NULL,
	id_giros_al_instante bigint NULL,
	id_banco_avvillas bigint NULL
)
;

CREATE TABLE detalle_cuenta_de_giros
(
	id_cuenta_de_giros bigint NOT NULL,
	fecha_de_activacion varchar(50) NULL,
	valor_del_giro double precision NULL,
	id_moneda_cuenta_giro bigint NULL,
	id_tipo_giro bigint NULL,
	tasa_de_interes double precision NULL,
	creado_por varchar(50) NULL,
	fecha_de_creacion date NULL,
	actualizado_por varchar(50) NULL,
	fecha_actualizada varchar(50) NULL,
	id_cuenta_giros bigint NULL
)
;

CREATE TABLE detalles_actividad_cuenta
(
	id_detalles_actividad_cuenta varchar(50) NULL,
	creado_por varchar(50) NULL,
	id_cuenta varchar(50) NULL,
	fecha_de_creacion varchar(50) NULL,
	actualizado_por varchar(50) NULL,
	fecha_de_actualizacion varchar(50) NULL,
	id_notas_cuenta varchar(50) NULL
)
;

CREATE TABLE fondo
(
	id_fondo bigint NULL,
	nombre_fondo varchar(50) NULL,
	id_Codigo_fondo bigint NULL,
	id_despachador_giros bigint NULL,
	id_despachador bigint NULL,
	id_banco_avvillas bigint NULL
)
;

CREATE TABLE Giro
(
	id_giros bigint NOT NULL,
	id_cliente bigint NULL,
	id_origen bigint NULL,
	Fecha_Giro date NULL,
	Costo_Giro double precision NULL,
	id_destino bigint NULL,
	id_pais bigint NULL,
	id_despachador_giros bigint NULL,
	id_despachador_giro bigint NULL
)
;

CREATE TABLE giro_pagado
(
	id_giro_pagado bigint NOT NULL,
	id_giro bigint NULL,
	id_tipo_de_pago integer NULL,
	cantidad_a_pagar double precision NULL,
	numero_de_recibo bigint NULL,
	fecha_de_envio date NULL,
	fecha_de_pago date NULL,
	id_entidad bigint NULL,
	comsion double precision NULL
)
;

CREATE TABLE historial_estado_de_cuenta
(
	id_historial_estado_de_cuenta varchar(50) NULL,
	id_cuenta varchar(50) NULL,
	nuevo_estado varchar(50) NULL,
	estado_antiguo varchar(50) NULL,
	cambiado_por varchar(50) NULL,
	fecha_cambiada varchar(50) NULL,
	id_pago bigint NULL
)
;

CREATE TABLE Negociacion
(
	idNegociacion integer NULL,
	idOrigen varchar(50) NULL,
	idBanco varchar(50) NULL,
	idDestino varchar(50) NULL,
	vigencia varchar(50) NULL,
	flete varchar(50) NULL,
	comision_Giro varchar(50) NULL,
	comision_Costo varchar(50) NULL,
	comision_Banco varchar(50) NULL,
	fecha_Creacion varchar(50) NULL,
	fecha_Finalizacion varchar(50) NULL,
	total_Giro varchar(50) NULL
)
;

CREATE TABLE notas_cuenta
(
	id_notas_cuenta varchar(50) NOT NULL,
	id_cuenta bigint NULL,
	nota varchar(50) NULL,
	fecha_de_comentario varchar(50) NULL,
	id_comentarista varchar(50) NULL
)
;

CREATE TABLE oferta_de_prestamo_encontrada
(
	id_oferta_de_prestamo_encontrada integer NOT NULL,
	id_encontrada varchar(50) NULL,
	id_oferta_de_producto varchar(50) NULL
)
;

CREATE TABLE Ordenante
(
	id_ordenante varchar(50) NOT NULL,
	nombre varchar(50) NULL,
	apellidos varchar(50) NULL,
	razon_social varchar(50) NULL,
	cuenta_origen_transferencia varchar(50) NULL
)
;

CREATE TABLE Pais
(
	id_pais varchar(50) NULL,
	nombre varchar(50) NULL,
	gentilicio_nal varchar(50) NULL
)
;

CREATE TABLE Producto
(
	codigo_Producto bigint NULL,
	nombre_tipo_producto varchar(50) NULL,
	id_categoria_producto bigint NULL,
	nombre_producto varchar(50) NULL,
	nombre_corto_producto varchar(50) NULL,
	Descripcion varchar(50) NULL,
	Fecha_inicio_producto date NULL,
	Fecha_final_producto date NULL,
	Estado boolean NULL,
	id_despachador bigint NULL,
	id_banco_avvillas bigint NULL
)
;

CREATE TABLE productos_en_oferta
(
	id_producto_oferta varchar(50) NULL,
	id_categoria_producto varchar(50) NULL,
	id_tipo_producto varchar(50) NULL,
	fecha_inicio varchar(50) NULL,
	fecha_caduca varchar(50) NULL,
	nombre_producto_oferta varchar(50) NULL,
	nombre_corto_producto_oferta varchar(50) NULL,
	estado_oferta varchar(50) NULL
)
;

CREATE TABLE tipo_de_producto
(
	id_tipo_de_producto varchar(50) NOT NULL,
	dias_de_retraso varchar(50) NULL,
	dias_de_latencia varchar(50) NULL,
	No_Version_producto varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE banco_calenio ADD CONSTRAINT PK_Table5
	PRIMARY KEY (id_banco_calenio)
;

CREATE INDEX IXFK_banco_avvillas_BANCOBBXXX_despachador_giros ON banco_calenio (id_despachador_giro ASC)
;

CREATE INDEX IXFK_banco_calenio_despachador_giros ON banco_calenio (id_despachador_giro ASC)
;

ALTER TABLE banco_corresponsal ADD CONSTRAINT PK_banco_corresponsal
	PRIMARY KEY (id_banco_corresponsal)
;

CREATE INDEX IXFK_banco_corresponsal_despachador_giros ON banco_corresponsal (id_despachador_giros ASC)
;

CREATE INDEX IXFK_banco_corresponsal_despachador_giros_02 ON banco_corresponsal (id_despachador_giro ASC)
;

ALTER TABLE banco_del_beneficiario ADD CONSTRAINT PK_banco_del_beneficiario
	PRIMARY KEY (id_banco_del_beneficiario)
;

CREATE INDEX IXFK_banco_del_beneficiario_despachador_giros ON banco_del_beneficiario (id_despachador_giros ASC)
;

CREATE INDEX IXFK_banco_del_beneficiario_despachador_giros_02 ON banco_del_beneficiario (id_despachador_giro ASC)
;

ALTER TABLE beneficiario ADD CONSTRAINT PK_Beneficiario
	PRIMARY KEY (id_beneficiario)
;

CREATE INDEX IXFK_beneficiario_despachador_giros ON beneficiario (id_despachador_giros ASC)
;

CREATE INDEX IXFK_beneficiario_despachador_giros_02 ON beneficiario (id_despachador_giro ASC)
;

ALTER TABLE Cliente ADD CONSTRAINT PK_Cliente
	PRIMARY KEY (id_Cliente)
;

ALTER TABLE comision ADD CONSTRAINT PK_Bancos
	PRIMARY KEY (id_banco_calenio)
;

CREATE INDEX IXFK_Bancos_despachador_giros ON comision (id_despachador_giros ASC)
;

CREATE INDEX IXFK_comision_despachador_giros ON comision (id_despachador_giro ASC)
;

ALTER TABLE comisiones_del_giro ADD CONSTRAINT PK_honorarios_del_giro
	PRIMARY KEY (id_comisiones_del_giro)
;

CREATE INDEX IXFK_honorarios_de_cuenta_pago_de_cuenta ON comisiones_del_giro (id_pago ASC)
;

ALTER TABLE comprobante_recibo_giro ADD CONSTRAINT PK_comprobante_recibo_giro
	PRIMARY KEY (id_comprobante_recibo_giro)
;

CREATE INDEX IXFK_comprobante_recibo_giro_despachador_giros ON comprobante_recibo_giro (id_despachador_giros ASC)
;

CREATE INDEX IXFK_comprobante_recibo_giro_despachador_giros_02 ON comprobante_recibo_giro (id_despachador_giro ASC)
;

ALTER TABLE cuenta_giros ADD CONSTRAINT PK_cuenta
	PRIMARY KEY (id_cuenta_giros)
;

CREATE INDEX IXFK_cuenta_cliente ON cuenta_giros (id_cuenta_giros ASC)
;

CREATE INDEX IXFK_cuenta_giros_usuario ON cuenta_giros (idUsuario ASC)
;

CREATE INDEX IXFK_cuenta_notas_cuenta ON cuenta_giros (id_notas_cuenta ASC)
;

CREATE INDEX IXFK_cuenta_pago_de_cuenta ON cuenta_giros ()
;

ALTER TABLE despachador_giros ADD CONSTRAINT PK_Table5
	PRIMARY KEY (id_despachador_giro)
;

ALTER TABLE detalle_cuenta_de_giros ADD CONSTRAINT PK_cuenta_de_ahorros
	PRIMARY KEY (id_cuenta_de_giros)
;

CREATE INDEX IXFK_cuenta_de_giros_cuenta_giros ON detalle_cuenta_de_giros (id_cuenta_giros ASC)
;

CREATE INDEX IXFK_detalles_actividad_cuenta_notas_cuenta ON detalles_actividad_cuenta (id_notas_cuenta ASC)
;

CREATE INDEX IXFK_fondo_banco_avvillas_BAVICOBBXXX ON fondo (id_despachador ASC)
;

CREATE INDEX IXFK_fondo_banco_calenio ON fondo (id_banco_avvillas ASC)
;

CREATE INDEX IXFK_fondo_despachador_giros ON fondo (id_despachador_giros ASC)
;

ALTER TABLE Giro ADD CONSTRAINT PK_Giros
	PRIMARY KEY (id_giros)
;

CREATE INDEX IXFK_Giro_despachador_giros ON Giro (id_despachador_giros ASC)
;

CREATE INDEX IXFK_Giro_despachador_giros_02 ON Giro (id_despachador_giro ASC)
;

ALTER TABLE giro_pagado ADD CONSTRAINT PK_cuenta_de_pago
	PRIMARY KEY (id_giro_pagado)
;

CREATE INDEX IXFK_pago_de_cuenta_cuenta ON giro_pagado (id_giro ASC)
;

CREATE INDEX IXFK_pago_de_cuenta_cuenta_02 ON giro_pagado (id_giro ASC)
;

CREATE INDEX IXFK_historial_estado_de_cuenta_pago_de_cuenta ON historial_estado_de_cuenta (id_pago ASC)
;

ALTER TABLE notas_cuenta ADD CONSTRAINT PK_notas_cuenta
	PRIMARY KEY (id_notas_cuenta)
;

CREATE INDEX IXFK_notas_cuenta_cuenta ON notas_cuenta (id_cuenta ASC)
;

ALTER TABLE oferta_de_prestamo_encontrada ADD CONSTRAINT PK_oferta_de_prestamo_encontrada
	PRIMARY KEY (id_oferta_de_prestamo_encontrada)
;

ALTER TABLE Ordenante ADD CONSTRAINT PK_Ordenante
	PRIMARY KEY (id_ordenante)
;

CREATE INDEX IXFK_Ordenante_Giros ON Ordenante (id_ordenante ASC)
;

CREATE INDEX IXFK_Producto_banco_avvillas_BAVICOBBXXX ON Producto (id_despachador ASC)
;

CREATE INDEX IXFK_Producto_banco_calenio ON Producto (id_banco_avvillas ASC)
;

ALTER TABLE tipo_de_producto ADD CONSTRAINT PK_tipo_de_producto
	PRIMARY KEY (id_tipo_de_producto)
;

/* Create Foreign Key Constraints */

ALTER TABLE banco_calenio ADD CONSTRAINT FK_banco_calenio_despachador_giros
	FOREIGN KEY (id_despachador_giro) REFERENCES despachador_giros (id_despachador_giro) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE banco_corresponsal ADD CONSTRAINT FK_banco_corresponsal_despachador_giros
	FOREIGN KEY (id_despachador_giro) REFERENCES despachador_giros (id_despachador_giro) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE banco_del_beneficiario ADD CONSTRAINT FK_banco_del_beneficiario_despachador_giros
	FOREIGN KEY (id_despachador_giro) REFERENCES despachador_giros (id_despachador_giro) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE beneficiario ADD CONSTRAINT FK_beneficiario_despachador_giros
	FOREIGN KEY (id_despachador_giro) REFERENCES despachador_giros (id_despachador_giro) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE comision ADD CONSTRAINT FK_comision_despachador_giros
	FOREIGN KEY (id_despachador_giro) REFERENCES despachador_giros (id_despachador_giro) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE comisiones_del_giro ADD CONSTRAINT FK_honorarios_de_cuenta_pago_de_cuenta
	FOREIGN KEY (id_pago) REFERENCES giro_pagado (id_giro_pagado) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE comprobante_recibo_giro ADD CONSTRAINT FK_comprobante_recibo_giro_despachador_giros
	FOREIGN KEY (id_despachador_giro) REFERENCES despachador_giros (id_despachador_giro) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE detalle_cuenta_de_giros ADD CONSTRAINT FK_cuenta_de_giros_cuenta_giros
	FOREIGN KEY (id_cuenta_giros) REFERENCES cuenta_giros (id_cuenta_giros) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE detalles_actividad_cuenta ADD CONSTRAINT FK_detalles_actividad_cuenta_notas_cuenta
	FOREIGN KEY (id_notas_cuenta) REFERENCES notas_cuenta (id_notas_cuenta) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE fondo ADD CONSTRAINT FK_fondo_banco_calenio
	FOREIGN KEY (id_banco_avvillas) REFERENCES banco_calenio (id_banco_calenio) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Giro ADD CONSTRAINT FK_Giro_despachador_giros
	FOREIGN KEY (id_despachador_giro) REFERENCES despachador_giros (id_despachador_giro) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE giro_pagado ADD CONSTRAINT FK_pago_de_cuenta_cuenta_02
	FOREIGN KEY (id_giro) REFERENCES cuenta_giros (id_cuenta_giros) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE historial_estado_de_cuenta ADD CONSTRAINT FK_historial_estado_de_cuenta_pago_de_cuenta
	FOREIGN KEY (id_pago) REFERENCES giro_pagado (id_giro_pagado) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE notas_cuenta ADD CONSTRAINT FK_notas_cuenta_cuenta
	FOREIGN KEY (id_cuenta) REFERENCES cuenta_giros (id_cuenta_giros) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE Producto ADD CONSTRAINT FK_Producto_banco_calenio
	FOREIGN KEY (id_banco_avvillas) REFERENCES banco_calenio (id_banco_calenio) ON DELETE Restrict ON UPDATE Restrict
;
